### ISSUE TITLE
Remove custom installer

### ISSUE THREAD

**Issue by sergiohinojosa** [keptn-sandbox/keptn-in-a-box#2]
Remove custom installer when --domain flag is available. 

Check if option Loadbalancer is accepted with Istio=Reuse

`--platform=kubernetes --istio-install-option=Reuse --gateway=LoadBalancer`

**Comment by sergiohinojosa** [comment]
Just let me know when the installer is available so I can test it. I need the following intall parameters

`--platform=kubernetes --istio-install-option=Reuse --gateway=LoadBalancer --domain=mydomain.com
`

**Comment by christian-kreuzberger-dtx** [comment]
We are in the process of implementing [KEP 18](https://github.com/keptn/enhancement-proposals/pull/18) for Keptn 0.7.0, which will give not provide those options in the installer, but give you full flexibility regarding those options as you can do it yourself (e.g., install istio and create a public-gateway with the domain mydomain.com).

**Comment by sergiohinojosa** [comment]
in 0.7 not needed any more. Custom installer is gone :D !
