### ISSUE TITLE
provide instructions for smaller installation

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn-sandbox/keptn-in-a-box#4]
The installer already has a couple of different flags to customize the installation.

- Please document them so I know how to use Keptn-in-a-box without e.g., the sample applications, or without istio. 
- Please document the resource footprint for a smaller installation (with the demo app in three stages)
- Please document how to use it without Dynatrace

**Comment by sergiohinojosa** [comment]
Done. see 

**installationModulesMinimal**

Keptn full installation runs with 2vCPU, 10 Gigs of disk and 4 Gigs of RAM. quite small huh? Tested on Ubuntu 18 and 20 LTS.
