### ISSUE TITLE
Better step-by-step documentation when installing keptn-in-a-box

### ISSUE THREAD

**Issue by grabnerandi** [keptn-sandbox/keptn-in-a-box#5]
I think we should provide a step-by-step guide that goes into the following detail

#1: Clone this GitHub Repo
```
$ git clone https://github.com/keptn-sandbox/keptn-in-a-box
$ cd keptn-in-a-box
``` 

#2: Provide input parameters in the script
``` 
$ vi keptn-in-a-box.sh
``` 
Here you need to at least provide TENANT, PAASTOKEN & APITOKEN
To disable certain installation options see the following table, e.g: show a table with all flags and what they mean

#3: execute the script
``` 
sudo ./keptn-in-a-box.sh
``` 

#4: Validate result
In order to validate the installation was successful open the log
``` 
cat /tmp/installer.log
``` 
If everything was fine you should be able to access the Keptn's bridge and Keptns API via https://bridge.keptn.1.2.3.4.nip.io & https://api.keptn.1.2.3.4.nip.io

In case of issues - please create an issue in this git repo and attach the installer.log file

**Comment by sergiohinojosa** [comment]
Done.
