### ISSUE TITLE
Provide install progress and final output

### ISSUE THREAD

**Issue by grabnerandi** [keptn-sandbox/keptn-in-a-box#6]
Right now the keptn-in-a-box.sh script is silent and doesnt give any indication on progress or final status.
I suggest to at least put some type of status information on the console, e.g: "installing mikrok8s", "installing activegate" .. -> so - at least provide the names of the high level installation steps

At the end of the installation I would like to see sometign like this
IN CASE OF SUCCESS
```
Installation Successful. You can access keptn via
* https://bridge.keptn.1.2.3.4.nip.io
* https://api.keptn.1.2.3.4.nip.io
``` 

IN CASE OF FAILURE
```
Installation failed. For more details please see /tmp/installer.log.
If you want to get this investigated please add an issue to the keptn-in-a-box github repo 
```

**Comment by sergiohinojosa** [comment]
The design of the script was made for running as root with no interactive shell for the automation of multiple instnaces, meaning passed by userdata at initialization. To see the output on realtime just type 

``` bash
less +F /tmp/installer.log
```

stderror and stdout are piped to the installer log. The modules that have been activated print out their high-level details.

This part of the script make the pipe:

``` bash
exec 3>&1 4>&2
trap 'exec 2>&4 1>&3' 0 1 2 3
exec 1>$LOGFILE 2>&1
```

**Comment by sergiohinojosa** [comment]
A better Description was added. Nevertheless the script should run in background but an option is added for not piping the stdout/err to the console.
